### ISSUE TITLE
Büyük Dosya Boyutları

### ISSUE THREAD

**Issue by msdundar** [bsaral/KHTS#6]
Evet şuan sunucuya 8mb'dan büyük dosya yüklemiyor ancak uygulama ilginç bir davranışta bulunuyor.

700mb'lık bir dosyayı yükletmek istediğimde, uygulama önce yüklemeyi yapıyor! - daha sonra tabloya ekleme ve sunucuda dosyayı kaydetme kontrolünü devreye sokuyor ve bu dosyayı /public altına kaydetmiyor.

Tüm bu süreci ifconfig ile izlersen daha anlaşılır olacaktır.

ifconfig (lo'da 3.7GB'lık bir trafik var mesela - benim yaptığım upload işleminden doğan):
![ifconfig](https://f.cloud.github.com/assets/468744/215147/b9edd416-8469-11e2-9b9c-db36921df940.png)

veya direk "ifconfig -s lo" - böyle sadece lo'yu görüntülersin:
![if-lo](https://f.cloud.github.com/assets/468744/215148/c379ab36-8469-11e2-99cb-54e15fca5acc.png)

**Comment by msdundar** [comment]
Tarayıcında ipucu verebilir bu durum hakkında:

![tarayici](https://f.cloud.github.com/assets/468744/215152/82514e24-846a-11e2-9acf-c43793ab5e36.png)

**Comment by bsaral** [comment]
Buna bir türlü anlam veremedim.File upload ile ilgili bir çok demo çalıştırdım hepsinde aynı şey oluyor.En basitinden https://github.com/tors/jquery-fileupload-rails-paperclip-example yereline indirip , upload.rb içerisine

`validates_attachment_size :upload, :in => 1...8.megabytes` 

ekleyip çalıştırdığında nasıl olduğunu görebilirsin.
