### ISSUE TITLE
Açıklama Alanı

### ISSUE THREAD

**Issue by msdundar** [bsaral/KHTS#9]
Dosya upload ekranında birde açıklama girilebilmesi için bir alan olması gerekiyor. Aksi halde "Yeni_metin_belgesi1.docx"in ne olduğunu her seferinde indirip öğrenmek gerekecek :)

Aşağıda bir örnek var, diğer issue'larda belirttiğim şeyleri ve bu açıklama kısmı olayını vs. işaretledim:

![ss](https://f.cloud.github.com/assets/468744/215207/2526c00a-8472-11e2-8729-22f66c128b47.png)

**Comment by bsaral** [comment]
@msdundar  açıklama alanı zorunlu tutulacak mı ?

**Comment by msdundar** [comment]
@bsaral Evet.
